spring.application.name=codechella

spring.r2dbc.url=r2dbc:postgresql://localhost:5434/codechella
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

spring.flyway.url=jdbc:postgresql://localhost:5434/codechella
spring.flyway.user=postgres
spring.flyway.password=postgres

translator.api.url=YOUR_API_URL
translator.api.key=YOUR_API_KEY